### ISSUE TITLE
Document Best Ways to get Help with django-import-export

### ISSUE THREAD

**Issue by mgrdcm** [django-import-export/django-import-export#1134]
Greetings!  This package being a fairly complicated tool, we often we get questions on usage in the form of Issues (for instance #1133).  I'd like to recommend we establish and document a preferred forum for those types of usage questions.  Perhaps that's still "create a GitHub issue and label it with `question`" (like this Issue), or "create a [Stack Overflow question tagged with `django-import-export`](https://stackoverflow.com/questions/tagged/django-import-export)", etc.

I'm happy to take on figuring this out and documenting!  Also apologies if I've missed that this is already established somewhere.  Does this seem like a good idea @bmihelac, @andrewgy8, @claudep, @manelclos, and @shaggyfrog?

**Comment by andrewgy8** [comment]
Yeah I think that is a great idea. Perhaps there is a way through the GitHub issue temple to mark them as issues. I know when I was setting it up, there were a couple of template options and iirc one was a question option like you mention.

**Comment by manelclos** [comment]
@mgrdcm great idea, I'd go for Stack Overflow, and also trying to improve the documentation where necessary 👍

**Comment by mgrdcm** [comment]
@andrewgy8 Oh nice, I didn't know that!  Looks like this is what you're talking about:  https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

So we could do a "Question" template type.  Looks like we can even automatically add labels like for instance `questions`.

And to @manelclos's point if we did want to direct people to create an appropriately-tagged question on SO, we could do it with this ["If you prefer to receive certain reports outside of GitHub..."](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) functionality:
```
Here is an example config.yml file.

blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
```

So far I think we should try out the custom issue types first.  We can go ahead and create custom issue types for `Bug report`, `Feature request`, and `Question` with a little bit of issue template for each and also set up appropriate label(s) so the Issues list is a little easier to parse.  We could even add an `Get Help on Stack Overflow` option there too just to see how it goes.  If we get too many questions then remove the on-GitHub `Question` type and just leave the `Get Help on Stack Overflow` one.

How does that sound?  I'm happy to work on that, but it looks like while I'm a member I don't have access to set up the Issue types.  We'd still want bmihelac sign-off in any case I think...
